### ISSUE TITLE
Delete fencing jobs upon their completion in the fence-controller

### ISSUE THREAD

**Issue by shradha741** [kvaps/kube-fencing#7]
Hi,
There has been some resistance in using the TTL controller to delete completed jobs since it is an Alpha feature.
I wanted to get your opinions on extending the fencing controller to delete the fencing job upon 
1. Successful completion of the job itself.
2. when the node moves back to the Ready state(irrespective of the status of the job).

I understand that this would not let the logs related to the fencing operation persist but it would remove the dependency on the TTL feature.

**Comment by kvaps** [comment]
Hi, I think your idea definitely makes sense.

It also can be optional, eg if `fencing/ttl=0` or unspecified, then fencing-controller will remove the jobs automatically, otherwise it will rely on TTL controller which is fine for debugging.

Also controller must delete the fencing job if node is back online on both cases, to avoid the situation when node was fenced with failed job, then it returns online and after a while it should be fenced again but job already existing,

**Comment by kvaps** [comment]
Should be fixed in `v2.1.0`.
Now all fencing jobs have OwnerReference set and node-controller removes fencing job when node returns online.
This approach is working quite well so I decided to deprecate TTL controller.

@shradha741 please confirm if this working to you.
